In [1]:
import numpy as np
import re

In [2]:
prefix = '..\\Ansys\\Outputs_RF\\'
filename = 'TrajSimTest.fld'

In [3]:
with open(prefix + filename) as f:
    lines = f.readlines()

# To remove parameters from memory, use:
# import gc
# del lines # Remove reference of the parameter
# gc.collect() # Remove unreferenced parameters from RAM

In [4]:
print(len(lines))
for line in lines[:5]:
    print(line)
for line in lines[-5:]:
    print(line)

2552013
Grid Output Min: [-8mm -6.5mm -1mm] Max: m 6.5mm 11mm] Grid Size: [0.1mm 0.1mm 0.1mm] 

X, Y, Z, Scalar data "Mag_E"

-8.0000000000000002e-03 -6.5000000000000006e-03 -1.0000000000000000e-03  1.8881072346060504e+04

-8.0000000000000002e-03 -6.5000000000000006e-03 -8.9999999999999998e-04  1.9265675534113820e+04

-8.0000000000000002e-03 -6.5000000000000006e-03 -8.0000000000000004e-04  1.9544073112644150e+04

8.0000000000000002e-03 6.5000000000000006e-03 1.0600000000000002e-02  1.0871428960785863e+03

8.0000000000000002e-03 6.5000000000000006e-03 1.0700000000000001e-02  1.0732677467315114e+03

8.0000000000000002e-03 6.5000000000000006e-03 1.0800000000000001e-02  1.0588551770807846e+03

8.0000000000000002e-03 6.5000000000000006e-03 1.0900000000000000e-02  1.0436732153094922e+03

8.0000000000000002e-03 6.5000000000000006e-03 1.0999999999999999e-02  1.0281009389108758e+03



In [5]:
lines[2].split(' ')[-1]

'1.8881072346060504e+04\n'

In [6]:
Ups = np.zeros(len(lines)-2)
for i, line in enumerate(lines[2:]):
    try:
        Ups[i] = float(line.split(' ')[-1])
    except:
        print(i, line.split(' ')[-1])

In [7]:
header = lines[0]
header

'Grid Output Min: [-8mm -6.5mm -1mm] Max: m 6.5mm 11mm] Grid Size: [0.1mm 0.1mm 0.1mm] \n'

In [8]:
min_match = re.search(r'Min: \[([^\]]+)\]', header)
max_match = re.search(r'Max: \[([^\]]+)\]', header)
size_match = re.search(r'Grid Size: \[([^\]]+)\]', header)

if min_match and max_match and size_match:
    min_vals = [float(val.replace('mm', 'e-3')) for val in min_match.group(1).split()]
    max_vals = [float(val.replace('mm', 'e-3')) for val in max_match.group(1).split()]
    grid_size_vals = [float(val.replace('mm', 'e-3')) for val in size_match.group(1).split()]
else:
    raise ValueError('无法解析文件头部的网格信息')

x_min, y_min, z_min = min_vals
x_max, y_max, z_max = max_vals
dx, dy, dz = grid_size_vals

In [9]:
print(x_min, y_min, z_min)
print(x_max, y_max, z_max)
print(dx, dy, dz)

-0.008 -0.0065 -0.001
0.008 0.0065 0.011
0.0001 0.0001 0.0001


In [10]:
X = np.arange(x_min, x_max + dx/2, dx)
Y = np.arange(y_min, y_max + dy/2, dy)
Z = np.arange(z_min, z_max + dz/2, dz)

In [11]:
xs, ys, zs = np.meshgrid(X, Y, Z, indexing='ij')
nx = len(X)
ny = len(Y)
nz = len(Z)

In [12]:
Up = Ups.reshape((nx, ny, nz))

In [13]:
Up

array([[[18881.07234606, 19265.67553411, 19544.07311264, ...,
          2517.44527907,  2474.55432375,  2437.44784617],
        [19439.1615347 , 19949.9372825 , 20346.25150548, ...,
          2511.15346244,  2468.2902138 ,  2431.02223723],
        [20216.8961653 , 20759.74696027, 21209.82003054, ...,
          2504.48590538,  2461.93275476,  2425.05472655],
        ...,
        [  330.31658318,   312.06067426,   299.8594488 , ...,
          1327.077024  ,  1307.53194624,  1287.96675123],
        [  273.23927676,   247.76662964,   229.48584137, ...,
          1326.96719717,  1307.45232307,  1287.91510475],
        [  225.92103748,   193.04790411,   167.26717778, ...,
          1326.94678681,  1307.4282348 ,  1286.6800403 ]],

       [[18991.76247086, 19382.44955912, 19667.71867338, ...,
          2524.60862582,  2481.70250846,  2443.29653178],
        [19559.3602518 , 20069.34129607, 20470.18659139, ...,
          2518.45449724,  2475.57542103,  2437.03025657],
        [20329.7917559 , 

In [14]:
xs

array([[[-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        ...,
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ]],

       [[-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        ...,
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079]],

       [[-0.0078, -0.0078, -0.0078, ..., -0.0078, -0.0078, -0.0078],
        [-0.0078, -0.0078, -0.0078, ..., -0.0078, -0.0078, -0.0078],
    

In [15]:
ys

array([[[-0.0065, -0.0065, -0.0065, ..., -0.0065, -0.0065, -0.0065],
        [-0.0064, -0.0064, -0.0064, ..., -0.0064, -0.0064, -0.0064],
        [-0.0063, -0.0063, -0.0063, ..., -0.0063, -0.0063, -0.0063],
        ...,
        [ 0.0063,  0.0063,  0.0063, ...,  0.0063,  0.0063,  0.0063],
        [ 0.0064,  0.0064,  0.0064, ...,  0.0064,  0.0064,  0.0064],
        [ 0.0065,  0.0065,  0.0065, ...,  0.0065,  0.0065,  0.0065]],

       [[-0.0065, -0.0065, -0.0065, ..., -0.0065, -0.0065, -0.0065],
        [-0.0064, -0.0064, -0.0064, ..., -0.0064, -0.0064, -0.0064],
        [-0.0063, -0.0063, -0.0063, ..., -0.0063, -0.0063, -0.0063],
        ...,
        [ 0.0063,  0.0063,  0.0063, ...,  0.0063,  0.0063,  0.0063],
        [ 0.0064,  0.0064,  0.0064, ...,  0.0064,  0.0064,  0.0064],
        [ 0.0065,  0.0065,  0.0065, ...,  0.0065,  0.0065,  0.0065]],

       [[-0.0065, -0.0065, -0.0065, ..., -0.0065, -0.0065, -0.0065],
        [-0.0064, -0.0064, -0.0064, ..., -0.0064, -0.0064, -0.0064],
    

In [16]:
zs

array([[[-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        ...,
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ]],

       [[-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        ...,
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ]],

       [[-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
    

In [17]:
import gc

del lines, Ups, X, Y, Z, xs, ys, zs, Up
gc.collect()

0

In [18]:
def MagE_from_file(filename):
    '''Read RF electric field magnitude data from an Ansys fld file and return result in grid shaped array'''
    
    # Open file and read content
    with open(filename) as f:
        lines = f.readlines()

    # Extract basic data from header
    header = lines[0]
    min_match = re.search(r'Min: \[([^\]]+)\]', header)
    max_match = re.search(r'Max: \[([^\]]+)\]', header)
    size_match = re.search(r'Grid Size: \[([^\]]+)\]', header)
    if min_match and max_match and size_match:
        min_vals = [float(val.replace('mm', 'e-3')) for val in min_match.group(1).split()]
        max_vals = [float(val.replace('mm', 'e-3')) for val in max_match.group(1).split()]
        grid_size_vals = [float(val.replace('mm', 'e-3')) for val in size_match.group(1).split()]
    else:
        raise ValueError('Unable to analyze the header')
    x_min, y_min, z_min = min_vals
    x_max, y_max, z_max = max_vals
    dx, dy, dz = grid_size_vals
    
    # Read file data
    Ups = np.zeros(len(lines)-2)
    for i, line in enumerate(lines[2:]):
        try:
            Ups[i] = float(line.split(' ')[-1])
        except:
            print('Error:', i, line.split(' ')[-1])

    # Generate the grid
    X = np.arange(x_min, x_max + dx/2, dx)
    Y = np.arange(y_min, y_max + dy/2, dy)
    Z = np.arange(z_min, z_max + dz/2, dz)
    xs, ys, zs = np.meshgrid(X, Y, Z, indexing='ij')
    nx = len(X)
    ny = len(Y)
    nz = len(Z)

    # Reshape the data
    MagE = Ups.reshape((nx, ny, nz))

    return xs, ys, zs, MagE

In [19]:
xs, ys, zs, Ups = MagE_from_file(prefix + filename)

In [20]:
Ups

array([[[18881.07234606, 19265.67553411, 19544.07311264, ...,
          2517.44527907,  2474.55432375,  2437.44784617],
        [19439.1615347 , 19949.9372825 , 20346.25150548, ...,
          2511.15346244,  2468.2902138 ,  2431.02223723],
        [20216.8961653 , 20759.74696027, 21209.82003054, ...,
          2504.48590538,  2461.93275476,  2425.05472655],
        ...,
        [  330.31658318,   312.06067426,   299.8594488 , ...,
          1327.077024  ,  1307.53194624,  1287.96675123],
        [  273.23927676,   247.76662964,   229.48584137, ...,
          1326.96719717,  1307.45232307,  1287.91510475],
        [  225.92103748,   193.04790411,   167.26717778, ...,
          1326.94678681,  1307.4282348 ,  1286.6800403 ]],

       [[18991.76247086, 19382.44955912, 19667.71867338, ...,
          2524.60862582,  2481.70250846,  2443.29653178],
        [19559.3602518 , 20069.34129607, 20470.18659139, ...,
          2518.45449724,  2475.57542103,  2437.03025657],
        [20329.7917559 , 

In [21]:
xs

array([[[-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        ...,
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ],
        [-0.008 , -0.008 , -0.008 , ..., -0.008 , -0.008 , -0.008 ]],

       [[-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        ...,
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079],
        [-0.0079, -0.0079, -0.0079, ..., -0.0079, -0.0079, -0.0079]],

       [[-0.0078, -0.0078, -0.0078, ..., -0.0078, -0.0078, -0.0078],
        [-0.0078, -0.0078, -0.0078, ..., -0.0078, -0.0078, -0.0078],
    

In [22]:
ys

array([[[-0.0065, -0.0065, -0.0065, ..., -0.0065, -0.0065, -0.0065],
        [-0.0064, -0.0064, -0.0064, ..., -0.0064, -0.0064, -0.0064],
        [-0.0063, -0.0063, -0.0063, ..., -0.0063, -0.0063, -0.0063],
        ...,
        [ 0.0063,  0.0063,  0.0063, ...,  0.0063,  0.0063,  0.0063],
        [ 0.0064,  0.0064,  0.0064, ...,  0.0064,  0.0064,  0.0064],
        [ 0.0065,  0.0065,  0.0065, ...,  0.0065,  0.0065,  0.0065]],

       [[-0.0065, -0.0065, -0.0065, ..., -0.0065, -0.0065, -0.0065],
        [-0.0064, -0.0064, -0.0064, ..., -0.0064, -0.0064, -0.0064],
        [-0.0063, -0.0063, -0.0063, ..., -0.0063, -0.0063, -0.0063],
        ...,
        [ 0.0063,  0.0063,  0.0063, ...,  0.0063,  0.0063,  0.0063],
        [ 0.0064,  0.0064,  0.0064, ...,  0.0064,  0.0064,  0.0064],
        [ 0.0065,  0.0065,  0.0065, ...,  0.0065,  0.0065,  0.0065]],

       [[-0.0065, -0.0065, -0.0065, ..., -0.0065, -0.0065, -0.0065],
        [-0.0064, -0.0064, -0.0064, ..., -0.0064, -0.0064, -0.0064],
    

In [23]:
zs

array([[[-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        ...,
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ]],

       [[-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        ...,
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ]],

       [[-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
        [-0.001 , -0.0009, -0.0008, ...,  0.0108,  0.0109,  0.011 ],
    

In [24]:
# Basic Trapping Paramenters
m = 9.1093837e-31
q = -1.60217663e-19
freq = 1.36e+09

# Calculate pseudopotential in J (not eV)
Ups = (q*Ups) ** 2 / (4 * m * (2*np.pi*freq) ** 2)

In [25]:
Ups

array([[[3.43943857e-20, 3.58098687e-20, 3.68522834e-20, ...,
         6.11440671e-22, 5.90783326e-22, 5.73198320e-22],
        [3.64577030e-20, 3.83987701e-20, 3.99395403e-20, ...,
         6.08388160e-22, 5.87796083e-22, 5.70180168e-22],
        [3.94333076e-20, 4.15794132e-20, 4.34018470e-20, ...,
         6.05161692e-22, 5.84772065e-22, 5.67384324e-22],
        ...,
        [1.05267667e-23, 9.39533630e-24, 8.67500476e-24, ...,
         1.69912960e-22, 1.64944889e-22, 1.60045530e-22],
        [7.20311750e-24, 5.92270186e-24, 5.08096305e-24, ...,
         1.69884838e-22, 1.64924800e-22, 1.60032695e-22],
        [4.92433503e-24, 3.59554250e-24, 2.69932827e-24, ...,
         1.69879612e-22, 1.64918723e-22, 1.59725911e-22]],

       [[3.47988414e-20, 3.62452892e-20, 3.73200503e-20, ...,
         6.14925310e-22, 5.94201419e-22, 5.75952413e-22],
        [3.69099568e-20, 3.88597929e-20, 4.04275895e-20, ...,
         6.11931010e-22, 5.91270987e-22, 5.73001933e-22],
        [3.98749457e-20, 

In [29]:
np.gradient(Ups, dx)

(array([[[ 4.04455677e-18,  4.35420553e-18,  4.67766872e-18, ...,
           3.48463828e-20,  3.41809252e-20,  2.75409290e-20],
         [ 4.52253798e-18,  4.61022823e-18,  4.88049216e-18, ...,
           3.54285027e-20,  3.47490402e-20,  2.82176486e-20],
         [ 4.41638178e-18,  4.51186717e-18,  4.68240628e-18, ...,
           3.73693973e-20,  3.53110571e-20,  2.63073123e-20],
         ...,
         [-2.32698521e-21, -3.25225125e-21, -3.90485957e-21, ...,
           1.50080777e-20,  1.47299312e-20,  1.44527609e-20],
         [-4.43546206e-22, -1.50692447e-21, -2.56456508e-21, ...,
           1.51177306e-20,  1.48378205e-20,  1.28513197e-20],
         [ 6.13395719e-22, -4.40429116e-22, -1.29298925e-21, ...,
           1.52279725e-20,  1.32462127e-20,  1.29014090e-20]],
 
        [[ 4.49967986e-18,  4.84658563e-18,  4.34479330e-18, ...,
           3.44311526e-20,  3.37744530e-20,  2.72328059e-20],
         [ 4.31566025e-18,  4.32610925e-18,  4.53831399e-18, ...,
           3.50138860